export enum ActivityStatus {
  ACTIVITY_STATUS_CONFIRMED = 'ACTIVITY_STATUS_CONFIRMED',
  ACTIVITY_STATUS_FAILED = 'ACTIVITY_STATUS_FAILED',
  ACTIVITY_STATUS_PENDING = 'ACTIVITY_STATUS_PENDING',
  ACTIVITY_STATUS_TIMED_OUT = 'ACTIVITY_STATUS_TIMED_OUT',
}
