#!/usr/bin/env node

const execute = require('child_process').execSync

// First two arguments are node and script name
const buildDir = process.argv[2] || 'build'

execute(`rimraf ${buildDir}`, { stdio: 'inherit' })
execute(`copy-aragon-ui-assets -n aragon-ui ./${buildDir}`, {
  stdio: 'inherit',
})

execute(
  `parcel build src/index.html --out-dir ./${buildDir} --public-url ./ --no-cache`,
  { stdio: 'inherit' }
)
