# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: staging deployment

on:
  push:
    branches:
      -  development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: yarn lint
      run: yarn run lint
    - name: now
      run: >
        now
        -A now-staging.json
        --confirm
        --prod
        --token=${{ secrets.ZEIT_TOKEN }}
    env:
      CI: true